### ISSUE TITLE
Demo不能正常访问了

### ISSUE THREAD

**Issue by LetMeFly666** [yanhaijing/linklink#1]
http://yanhaijing.github.com/linklink 变成了404页面
或者说我应该这么提issue吗
希望没有打扰到大佬

**Comment by x1ntt** [comment]
https://yanhaijing.com/linklink/new.html

**Comment by LetMeFly666** [comment]
> https://yanhaijing.com/linklink/new.html

感谢~~风纪委员~~的提醒~👍
